# SPDX-License-Identifier: LGPL-3.0-only

# This file contains the pipelines that run on the SKA repository of Radler,
# which is at https://gitlab.com/ska-telescope/sdp/ska-sdp-func-radler

include:
  - local: .gitlab-ci.common.yml
  # Create Gitlab CI badges from CI metrics
  # https://developer.skao.int/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
  - project: ska-telescope/templates-repository
    file: gitlab-ci/includes/post_step.yml

# Caching 'public' allows keeping the 'pages' output of multiple branches / MRs.
cache:
  paths:
    - public

pages:
  stage: documentation
  needs: ["versioning","test-2204"]
  image: $BASE_IMAGE_2204
  script:
    - echo Deploying GitLab pages to $CI_PAGES_URL/$CI_COMMIT_REF_SLUG
    - mkdir -p public/$CI_COMMIT_REF_SLUG/coverage
    - cp doc/pages-index.html public/$CI_COMMIT_REF_SLUG/index.html
    - gcovr -j`nproc` -a coverage.json --html-details public/$CI_COMMIT_REF_SLUG/coverage/index.html
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - public
    expire_in: 1 week
